### ISSUE TITLE
Create Flowstate Project

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/farcastle#21]
https://flowstate.network/projects/0xe63af8334f5064564e7336996e1c99137c6ca496058de6d159108fae6670e743?chainId=8453

still needs
- [x] @earth2travis review
- [x] banner image (3x1 ratio, smaller than 1mb)

**Comment by earth2travis** [comment]
## Direct Donation

Share a direct link to checkout with your grant with your community on social, newsletters, etc.
https://flowstate.network/pool/?poolId=63&chainId=8453&recipientId=0x4dac1b9b5e713f42d107f500359d5f4617355a8f

## Farcaster Frame

Share your project-specific Frame on Farcaster for users to check your current matching multiplier & jump to checkout.
https://frames.flowstate.network/frames/grantee/0x4dac1b9b5e713f42d107f500359d5f4617355a8f/63/8453

**Comment by earth2travis** [comment]
We's gots ta shill
