### ISSUE TITLE
Purchase and Configure Quarters Channel

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/farcastle#45]
- Name: Quarters of the Hollow Servants
- `/quarters`
- Description: 

## Avatars

![Image](https://github.com/user-attachments/assets/ec2dea2a-9829-4f09-9386-32f5dcd5c26c)

## Banners

![Image](https://github.com/user-attachments/assets/ff01f9ae-b9d9-4b0d-9911-ae2f170c1c0f)

![Image](https://github.com/user-attachments/assets/67cd94ea-0a54-4501-9bad-5b7dd2441dbb)

**Comment by earth2travis** [comment]
> Creating the /quarters channel should be done soon. This will also help us activate the Farcastle Fellowship. We just need to set the expectations that it is ephemeral and experimental and will change often as we try different things.

**Comment by skuhlmann** [comment]
NEXT STEPS:
Turn the mod bot set up into a docs page in the website.

@earth2travis Should that be a different ticket?
