### ISSUE TITLE
Test Tokengating Quarters Channel

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/farcastle#54]
**OUTPUT**
Evaluate each solution
- does this work with moloch daos?
- do we want to recommend this option in our documentation?
  - if so, document the setup steps to convert to docs page
- is there a deeper/more seamless integration we can implement with any of these?

**Options**

- [x] Modbot
https://modbot.sh/

- [ ] Channel kit
https://github.com/zachterrell57/channel-kit
- pushing this out

- [x] Cura
https://cura.openrank.com/

-  ~~moxie/fan tokens~~

**Results for docs**
[Modbot](https://hackmd.io/T6dglPGoRVuFitgVwA3ylg)

**Background on channel changes**
https://hackmd.io/R09VL7U8SkaynVQU75QOJg

**Other considerations**
Most of these solutions gate the invite link. Are we worried about revoking membership if the token is no longer held by an existing member?

**Comment by skuhlmann** [comment]
**Curabot results**

https://hackmd.io/ZDikaNc-Rv2IxBS2ifEyFA

Takeaways
- good tool to help moderation
- auto invite might be nice for user discovery
- not sure it's working yet

**Comment by skuhlmann** [comment]
https://hackmd.io/PQD660l0T5y62fi3tmXuAg

here is a draft of the scroll

**Comment by earth2travis** [comment]
Scrolls are live: https://github.com/HausDAO/farcastle/issues/67
