### ISSUE TITLE
Apply to Octant Community Fund

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/farcastle#61]
Community Fund 2 - Application deadline: 22 November ⛔

https://app.charmverse.io/octant-community-fund/octant-community-fund-hq-8956739992421918

https://x.com/OctantApp/status/1859306834030625159

**Comment by skuhlmann** [comment]
Application deadline is 11/23

**Comment by earth2travis** [comment]
Looks like we missed this one: https://x.com/OctantApp/status/1859645167596339396

**Comment by earth2travis** [comment]
Here is the application:

## Welcome!  

☀️  

When first starting your application, make sure to create a proper title and select the appropriate template found in the 'category' section.  

---

### Please remember:  

- You need to regularly check the **Home Page** and any comments on your application.  
- By submitting a proposal, you understand that just participating does not guarantee that you will be chosen as a finalist for a grant.  
- You recognize that the Grants Council's review of your project does not mean they endorse its quality, effectiveness, or significance.  
- You agree not to hold anyone involved in the grants process responsible for anything that might happen related to your participation.  
- You also understand that if your project is selected as a finalist, there will be additional conditions to receive the grant.  

### Application Form  

#### Which Funding Directive are you applying to?*  

**Select one** Funding Directives.  

#### Project*  

Provide a brief description of your project.  

#### Requested Budget*  

How much **ETH** are you requesting? Include a detailed budget breakdown.  

#### Budget Justification*  

Can you explain the justification for the requested budget in detail?  

#### Objective*  

Describe the **primary goals** of your project.  

#### What is the intended impact on the Octant ecosystem, and how will this project contribute to the selected Funding Directive?  

---

### Roadmap Details*  

- Outline the **project roadmap**, detailing any major milestones or phases, with estimated timelines for each.  
- How will you **measure progress or success** at each stage of the project?  

---

### Team Details*  

- Provide details about your **team**.  
- What relevant experience does each team member bring to this project, and what will each person’s role entail?  
- Do any team members have a track record in this area? If so, please share any **prior accomplishments** or related projects.  

---

### Octant Specificity*

- If your project succeeds, what is the **potential impact** to the Octant ecosystem?  
- What makes your project **unique** or especially valuable to Octant?  

---

### Anything else? 

- Imagine you're us, is there anything else we should know?  

---

#### Milestone* 

Define and outline your key milestones.

**Comment by earth2travis** [comment]
Epoch 6 Application: https://github.com/orgs/HausDAO/projects/29/views/2?pane=issue&itemId=87709749

**Comment by earth2travis** [comment]
Still feel terrible about missing this. The community growth aligns well with levels 5 & 6. It would have set up well for some performance art to compliment Octant's Degens & Dragons campaign. And we had like 3 supporters on the board reviewing the applications.
